name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install --frozen-lockfile

    - name: Verify installation
      run: |
        node --version
        npm --version
        ls -la node_modules/.bin/vite || echo "Vite not found in node_modules/.bin"
        npm ls vite

    - name: Build
      run: |
        export PATH="$PATH:./node_modules/.bin"
        npm run build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./dist

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v2
