name: Test Build

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Debug environment
      run: |
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Current directory: $(pwd)"
        echo "Contents:"
        ls -la
        
    - name: Install dependencies
      run: |
        npm install --frozen-lockfile
        
    - name: Debug after install
      run: |
        echo "node_modules/.bin contents:"
        ls -la node_modules/.bin/ | head -20
        echo "Vite location:"
        which vite || echo "vite not in PATH"
        echo "NPX vite version:"
        npx vite --version
        
    - name: Test build
      run: |
        npm run build
        echo "Build completed successfully!"
        echo "Dist contents:"
        ls -la dist/
